version: "3"

services:
  social:
    build:
      context: .
      dockerfile: build/social.Dockerfile
    environment:
      DATASTORE_PROJECT_ID: superhuman-social
      DATASTORE_EMULATOR_HOST: datastore_emulator:8081
      GOOGLE_CLOUD_PROJECT: superhuman-social
      CLEARBIT_API_KEY: ${CLEARBIT_API_KEY}
    ports:
      - "8080:8080"