version: "3"

services:
  social:
    build:
      context: .
      dockerfile: build/social.Dockerfile
    environment:
      DATASTORE_PROJECT_ID: superhuman-social
      DATASTORE_EMULATOR_HOST: 0.0.0.0:7070
      GOOGLE_CLOUD_PROJECT: superhuman-social
      CLEARBIT_API_KEY: sk_49c5ad9208c03e6b0d3e4f719592efc9
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - datastore_emulator

  datastore_emulator:
    image: singularities/datastore-emulator
    environment:
      DATASTORE_PROJECT_ID: superhuman-social
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:7070
    ports:
      - "7070:7070"
    command: --no-store-on-disk

  datastore_viewer:
    image: skarpdev/google-datastore-ui:1.0.0
    environment:
      DSUI_PROJECT_ID: superhuman-social
      DSUI_PORT: 7071
      DSUI_DATASTORE_ENDPOINT: datastore_emulator:7070
    depends_on:
      - datastore_emulator
    ports:
      - "7071:7071"